# Generated by Django 3.1 on 2021-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'In Stock'), ('out of stock', 'Out of Stock'), ('await', 'Awaiting')], max_length=20),
        ),
    ]
